# Creates a Node.js build environment
# See Readme
# docker build -f Dockerfile.build -t cardano/node-build:latest .

FROM    node:6.9.4

ADD build.sh /tmp/build.sh
RUN chmod 744 /tmp/build.sh

CMD /tmp/build.sh