
version: '2'

services:
  api:
    image: cardano/rancher-jenkins-sample-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8081:8081
      - 5858:5858
    volumes:
      - .:/usr/src/app
    ## set your startup file here
    command: node --debug=5858 app.js
