# Compose containers for this application
#
# docker-compose up --build

version: '2'
services:

  api:
    image: cardano/node-release:latest
    build:
      context: .
      dockerfile: Dockerfile.release
    container_name: rancher_api_release
    ports:
      - "80:8080"
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
      PORT: 8080
      MONGO_URI: mongodb://mongo:27017/rancher_jenkins
      MONGO_SEED: "true"
      MONGO_SEED_COUNT: 20
      LOGGING_LEVEL: info
      CONFIG_ENV: release

  mongo:
    image: mongo:3
    command: mongod --smallfiles
