
version: '2'

services:
  api:
    image: cardano/rancher-jenkins-sample-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8081:8081
